tap "databricks/tap"
tap "koekeishiya/formulae"
brew "ack"
brew "pycparser"
brew "cffi"
brew "libssh"
brew "ansible"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "gettext"
brew "glib"
brew "cairo"
brew "harfbuzz"
brew "openjdk@17"
brew "apache-spark"
brew "arp-scan"
brew "awscli"
brew "bchunk"
brew "binutils"
brew "ccrypt"
brew "openjdk"
brew "clojurescript"
brew "cmake"
brew "coreutils"
brew "docutils"
brew "duckdb"
brew "enscript"
brew "flac"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "leptonica"
brew "libass"
brew "libbluray"
brew "libvorbis"
brew "opus"
brew "pango"
brew "sdl2"
brew "srt"
brew "tesseract"
brew "zeromq"
brew "ffmpeg"
brew "fzf"
brew "gawk"
brew "gcc"
brew "libavif"
brew "gd"
brew "gdk-pixbuf"
brew "gh"
brew "ghostscript"
brew "git-lfs"
brew "spirv-tools"
brew "glslang"
brew "go"
brew "pkgconf"
brew "gobject-introspection"
brew "netpbm"
brew "gts"
brew "librsvg"
brew "libtool"
brew "graphviz"
brew "guile"
brew "htop"
brew "httpie"
brew "shared-mime-info"
brew "libheif"
brew "libomp", link: true
brew "libraw"
brew "imagemagick"
brew "iperf3"
brew "jq"
brew "kakoune"
brew "librdkafka"
brew "kcat"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"
brew "leiningen"
brew "libmagic"
brew "llama.cpp"
brew "llvm"
brew "ruby"
brew "macvim"
brew "mad"
brew "make"
brew "mas"
brew "rust"
brew "maturin"
brew "ninja"
brew "meson"
brew "minio-mc"
brew "molten-vk"
brew "neovim"
brew "nghttp2"
brew "nmap"
brew "node"
brew "openjdk@11"
brew "openssl@1.1"
brew "pkcs11-helper"
brew "openvpn"
brew "opusfile"
brew "postgresql@14", restart_service: :changed
brew "pv"
brew "tcl-tk"
brew "python-tk@3.12"
brew "python@3.10"
brew "python@3.11"
brew "python@3.9"
brew "qemu"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "rustup"
brew "sc-im"
brew "socat"
brew "speedtest-cli"
brew "sshuttle"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "uv"
brew "vulkan-headers"
brew "watch"
brew "wget"
brew "wireshark"
brew "wrk"
brew "youtube-dl"
brew "z"
brew "zsh"
brew "databricks/tap/databricks"
brew "koekeishiya/formulae/yabai"
cask "docker"
cask "flycut"
cask "google-chrome"
cask "gstreamer-development"
cask "gstreamer-runtime"
cask "rar"
cask "telegram"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
mas "AdBlock Pro", id: 1018301773
mas "Flycut", id: 442160987
mas "G2FA", id: 6444865161
mas "HP Smart", id: 1474276998
mas "iMovie", id: 408981434
mas "Keeper Password Manager", id: 414781829
mas "Keynote", id: 409183694
mas "Kindle Classic", id: 405399194
mas "Menu Bar Calendar", id: 1558360383
mas "Microsoft Excel", id: 462058435
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "Vimari", id: 1480933944
mas "Windows App", id: 1295203466
mas "Wokabulary", id: 1667619825
vscode "alexcvzz.vscode-sqlite"
vscode "betterthantomorrow.calva"
vscode "betterthantomorrow.calva-spritz"
vscode "brunoventura.sqltools-athena-driver"
vscode "gerane.theme-idlefingers"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-pg"
vscode "mtxr.sqltools-driver-sqlite"
vscode "pdconsec.vscode-print"
vscode "ultram4rine.sqltools-clickhouse-driver"
vscode "vscodevim.vim"
