#!/bin/sh
.git/hooks/ctags >/dev/null 2>&1 &

[ -f Gemfile ] && bundle install > /dev/null &
[ -f db/schema.rb ] && bundle exec rake db:migrate > /dev/null &
[ -f db/schema.rb ] && RAILS_ENV=test bundle exec rake db:schema:load > /dev/null &
